let
    lista_fechas=Table.Column(lu_tiempo,"aniomesdía"),
    fecha_minima=List.Min(lista_fechas),
    fecha_maxima=List.Max(lista_fechas),
    dias=Number.From(fecha_maxima-fecha_minima)+1,
    fechas=List.Dates(fecha_minima,dias, #duration(1,0,0,0)),
    #"Convertida en tabla" = Table.FromList(fechas, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
    #"Tipo cambiado" = Table.TransformColumnTypes(#"Convertida en tabla",{{"Column1", type date}}),
    #"Columnas con nombre cambiado" = Table.RenameColumns(#"Tipo cambiado",{{"Column1", "Date"}}),
    #"Año insertado" = Table.AddColumn(#"Columnas con nombre cambiado", "Año", each Date.Year([Date]), Int64.Type),
    #"Mes insertado" = Table.AddColumn(#"Año insertado", "Mes", each Date.Month([Date]), Int64.Type),
    #"Día insertado" = Table.AddColumn(#"Mes insertado", "Día", each Date.Day([Date]), Int64.Type),
    #"Tipo cambiado1" = Table.TransformColumnTypes(#"Día insertado",{{"Mes", type text}}),
    #"Valor reemplazado" = Table.ReplaceValue(#"Tipo cambiado1","1","01",Replacer.ReplaceValue,{"Mes"}),
    #"Valor reemplazado1" = Table.ReplaceValue(#"Valor reemplazado","2","02",Replacer.ReplaceValue,{"Mes"}),
    #"Valor reemplazado2" = Table.ReplaceValue(#"Valor reemplazado1","3","03",Replacer.ReplaceValue,{"Mes"}),
    #"Valor reemplazado3" = Table.ReplaceValue(#"Valor reemplazado2","4","04",Replacer.ReplaceValue,{"Mes"}),
    #"Valor reemplazado4" = Table.ReplaceValue(#"Valor reemplazado3","5","05",Replacer.ReplaceValue,{"Mes"}),
    #"Valor reemplazado5" = Table.ReplaceValue(#"Valor reemplazado4","6","06",Replacer.ReplaceValue,{"Mes"}),
    #"Valor reemplazado6" = Table.ReplaceValue(#"Valor reemplazado5","7","07",Replacer.ReplaceValue,{"Mes"}),
    #"Valor reemplazado7" = Table.ReplaceValue(#"Valor reemplazado6","8","08",Replacer.ReplaceValue,{"Mes"}),
    #"Valor reemplazado8" = Table.ReplaceValue(#"Valor reemplazado7","9","09",Replacer.ReplaceText,{"Mes"}),
    #"Tipo cambiado2" = Table.TransformColumnTypes(#"Valor reemplazado8",{{"Día", type text}}),
    #"Valor reemplazado9" = Table.ReplaceValue(#"Tipo cambiado2","1","",Replacer.ReplaceValue,{"Día"}),
    #"Tipo cambiado3" = Table.TransformColumnTypes(#"Valor reemplazado9",{{"Año", type text}}),
    #"Columna combinada insertada" = Table.AddColumn(#"Tipo cambiado3", "Combinada", each Text.Combine({[Año], [Mes], [Día]}, ""), type text),
    #"Columnas con nombre cambiado1" = Table.RenameColumns(#"Columna combinada insertada",{{"Combinada", "aniomes"}}),
    #"Tipo cambiado4" = Table.TransformColumnTypes(#"Columnas con nombre cambiado1",{{"aniomes", Int64.Type}})
in
    #"Tipo cambiado4"